[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "crc-bank"
dynamic = ["version"]
description = "Banking application for resource allocation in Slurm based HPC systems."
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.7"
keywords = ["pitt", "crc", "hpc", "banking", "slurm"]
classifiers = [
    "Intended Audience :: System Administrators",
    "Natural Language :: English",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering",
    "Topic :: System :: Systems Administration",
]
dependencies = [
    "beautifulsoup4",
    "pandas",
    "prettytable",
    "python-environ",
    "SQLAlchemy",
    "sqlalchemy-utils",
    "time-machine",
]

[project.optional-dependencies]
docs = [
    "sphinx",
    "sphinx_autodoc_typehints",
    "sphinx-copybutton",
    "sphinx-rtd-theme",
    "sphinx-argparse",
]
tests = ["coverage"]

[tool.setuptools]
packages = ['bank']

[tool.setuptools.dynamic]
version = { attr = "bank.__version__" }