name: Documentation

on:
  pull_request:
  push:
    branches: [ development ]

permissions:
  contents: read
  packages: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/pitt-crc/test-env-slurm-22-05-2-1:v0.2.2
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Setup environment
        run: /usr/local/bin/entrypoint.sh

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip3.9 install .[docs]

      - name: Build documentation
        working-directory: docs
        run: make html SPHINXOPTS="-W"

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/build/html

  deploy:
    name: Publish Documentation
    if: github.event_name == 'push'
    needs: [ build ]

    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1