name: Build Documentation

on:
  workflow_dispatch:
  workflow_call:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/pitt-crc/test-env-slurm-22-05-2-1:v0.3.2
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Setup environment
        run: /usr/local/bin/entrypoint.sh

      - name: Checkout project source
        uses: actions/checkout@v3

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.3
        with:
          virtualenvs-create: false

      - name: Install dependencies
        run: poetry install --with docs

      - name: Build documentation
        working-directory: docs
        run: make html SPHINXOPTS="-W"

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/build/html
