name: Tests

on:
  workflow_dispatch:
  push:

jobs:
  python_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        slurm:
          - slurm-20-02-5-1
          - slurm-20-11-9-1
          - slurm-22-05-2-1
        python:
          - 3.8
          - 3.9

    steps:
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout source
        uses: actions/checkout@master

      - name: Build test environment
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: py-${{ matrix.python }}-${{ matrix.slurm }}
          build-args: SLURM_TAG=${{ matrix.slurm }}

      - name: Run tests
        uses: addnab/docker-run-action@v3
        with:
          image: py-${{ matrix.python }}-${{ matrix.slurm }}
          options: -v ${{ github.workspace }}:/app
          run: |
            bash /usr/local/bin/entrypoint.sh

            # Run tests with coverage and catch the exit status
            coverage-${{ matrix.python }} run -m unittest discover /app
            status=$?

            coverage-${{ matrix.python }} report --include="/app/bank/*"
            coverage-${{ matrix.python }} xml --include="/app/bank/*" -o app/coverage.xml
            exit $status  # Exit with the appropriate status

      # Report test coverage to codacy for the python version being tested
      - name: Report partial coverage results
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report --partial -l Python -r coverage.xml
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

  codacy-coverage-reporter:
    name: Report code coverage
    runs-on: ubuntu-latest
    needs: python_tests
    steps:

      # Tell codacy we are done reporting test coverage
      - name: Finish reporting coverage
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) final
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
